+: ✅ {user1} оказал уважение {user2}
'-': ⛔️ {user1} незауважал {user2}
буп: 🙃 {user1} сделал буп в носик {user2}
вдарить леща: 🖐️ {user1} вдарил(а) {user2} леща
вдарить под дых: 💥 {user1} вдарил(а) под дых {user2}
вернуть: ↩️ {user1} вернул(а) {user2}
взбить подушку: 🛏️ {user1} взбил(а) подушечку для {user2}
взять в рабство: 🧷 {user1} взял(а) в рабство {user2}
взять на ручки: 🧸 {user1} взял(а) {user2} на ручки
взять печеньку: 🍪 {user1} взял(а) печеньку у {user2}
влепить пенделя: 🥾 {user1} влепил(а) пенделя {user2}
вломить: 🥊 {user1} вломил(а) {user2}
влюбиться в: 💘 {user1} влюбился(ась) в {user2}
вместо тысячи слов: '{user2} бубубу бебебе'
воскресить: 🧙‍♂️ {user1} воскресил(а) {user2}
впечатлить: 🌟 {user1} впечатлил(а) {user2}
вручить корону: 👑 {user1} вручил(а) корону {user2}
вручить медаль: 🏅 {user1} вручил(а) медаль {user2}
вручить цветочек: 🌸 {user1} вручил(а) цветочек {user2}
вставить кляп: 🔇 {user1} вставил(а) кляп {user2}
выебать в жопу и анус: 🔇 {user1} выебал {user2} в жопу и анус
вызвать на дуэль: ⚔️ {user1} вызвал(а) {user2} на дуэль
вылизать тарелку: 🍽️ {user1} вылизал(а) тарелку рядом с {user2}
вынести: 🚪 {user1} вынес(ла) {user2}
выпить за: 🥂 {user1} выпил(а) за {user2}
выплюнуть: 🤮 {user1} выплюнул(а) {user2}
выпороть: 🪓 {user1} выпорол(а) {user2}
вырубить: 🥴 {user1} вырубил(а) {user2}
гладить: 🖐️ {user1} погладил(а) {user2}
гладить котика: '{user1} погладил котика {user2}'
гладить по голове: 🐾 {user1} погладил(а) {user2} по голове
дать: 🎁 {user1} дал(а) {user2}
дать верёвку: 🪢 {user1} дал(а) верёвку {user2}
дать поддых: 🥊 {user1} дал(а) {user2} поддых
дать попить: 🥤 {user1} дал(а) попить {user2}
депортировать: ✈️ {user1} депортировал(а) {user2}
держи отвёртку: 🪛 {user1} передал отвёртку {user2}
докс: 🕵️ {user1} задоксил(а) {user2}
дразнить: 😜 {user1} дразнил(а) {user2}
ебать: 🍆 {user1} выебал(а) {user2}
забайтить: 🪤 {user1} забайтил(а) {user2}
завалить на кровать: 🛏️ {user1} завалил(а) {user2} на кровать
заварить чаю: 🫖 {user1} заварил чаю для {user2}
завернуть в плед: 🛏️ {user1} завернул(а) {user2} в плед
завязать глаза: 🫣 {user1} завязал(а) глаза {user2}
загипнотизировать: 🌀 {user1} загипнотизировал(а) {user2}
загладить: 🙏 {user1} загладил(а) {user2}
загладить вину: 😓 {user1} попытался(ась) загладить вину перед {user2}
заглянуть в глаза: 👁️‍🗨️ {user1} заглянул(а) в глаза {user2}
заглянуть под юбку: 🔍 {user1} заглянул(а) под юбку {user2}
задудосить: 🌐 {user1} задудосил(а) {user2}
задушить ляшками: 🍗 {user1} задушил(а) {user2} ляшками
задушнить: 🤐 {user1} задушнил(а) {user2}
заебашить: 🔥 {user1} заебашил(а) {user2}
заказать спортиков: 📦 {user1} заказал(а) спортиков на адрес {user2}
закидать камнями: 🪨 {user1} закидал(а) {user2} камнями
заколдовать: ✨ {user1} заколдовал(а) {user2}
закормить до смерти: 🍰 {user1} закормил(а) {user2} до смерти
закормить печеньками: 🍪 {user1} закормил(а) {user2} печеньками
закутать в одеялко: 🛌 {user1} закутал(а) {user2} в одеялко
залезть на ручки: 🧸 {user1} залез(ла) на ручки к {user2}
замурлыкать: 🐱 {user1} замурлыкал(а) рядом с {user2}
заобнимать: 🐙 {user1} заобнимал(а) {user2}
запеленать: 🍼 {user1} запеленал(а) {user2}
запихнуть в мешок: 🧳 {user1} запихнул(а) {user2} в мешок
заплакать: 😭 {user1} заплакал(а) из-за {user2}
заплести косу: 🧶 {user1} заплёл(а) косу {user2}
запустить тапок: 🥿 {user1} запустил(а) тапок в {user2}
зарезать: 🔪 {user1} зарезал(а) {user2}
заскамить: 🎣 {user1} заскамил(а) {user2}
засосать: 💋 {user1} засосал(а) {user2}
засосать в омут любви: 💘 {user1} засосал(а) {user2} в омут любви
заставить ебашить: 🔨 {user1} заставил(а) {user2} ебашить
застрелить: 🔫 {user1} застрелил(а) {user2}
заткнуть кляпом: 🔇 {user1} заткнул(а) {user2} кляпом
затрахал: 💦 {user1} затрахал(а) {user2}
затрахать: 💦 {user1} затрахал(а) {user2}
затроллить: 🧌 {user1} затроллил(а) {user2}
затушить сигарету: 🚬 {user1} затушил(а) сигарету об {user2}
захайпить: 🔥 {user1} захайпил(а) {user2}
захвалить: 🎉 {user1} захвалил(а) {user2}
зацеловать: 😘 {user1} зацеловал(а) {user2}
избить: 🥊 {user1} избил(а) {user2}
извини: 🙏 {user1} извинился(ась) перед {user2}
кинуть взгляд: 👁️ {user1} кинул(а) взгляд на {user2}
кинуть под автобус: 🚌 {user1} кинул(а) {user2} под автобус
купить: 🛒 {user1} купил(а) {user2}
кусать: 🐾 {user1} укусил(а) {user2}
кусь: 🐾 {user1} укусил(а) {user2}
лечь в кровать: 🛏️ {user1} лёг(ла) в кроватку к {user2}
лечь на коленки: 🦵 {user1} лёг(ла) на коленки {user2}
лечь рядом: 💤 {user1} лёг(ла) рядом с {user2}
лизать: 👅 {user1} облизнул(а) {user2}
лизь: 👅 {user1} облизнул(а) {user2}
медаль: 🏅 {user1} наградил(а) {user2} медалью
мобилизировать: 🫡 {user1} мобилизировал(а) {user2} на важное дело
набросить покрывало: 🛏️ {user1} набросил(а) покрывало на {user2}
наброситься: 🙀 {user1} набросился(ась) на {user2}
наброситься с обнимашками: 💞 {user1} набросился(ась) на {user2} с обнимашками
надеть наручники: 🔗 {user1} надел(а) наручники на {user2}
надругатся: 🔞 {user1} надругался(ась) над {user2}
надуть губки: 😗 {user1} надул(а) губки на {user2}
накинуть плед: 🛋️ {user1} накинул(а) плед на {user2}
наклеить стикер: 🏷️ {user1} наклеил(а) стикер на {user2}
накормить: 🍽️ {user1} накормил(а) {user2}
налить ванну: 🛁 {user1} налил(а) ванну для {user2}
напоить кофем: ☕ {user1} напоил(а) {user2} кофем
напоить чаем с печеньками: 🍵 {user1} напоил(а) {user2} чаем с печеньками
напугать: 😱 {user1} напугал(а) {user2}
нарисовать сердечко: ❤️ {user1} нарисовал(а) сердечко для {user2}
насвистать: 🎵 {user1} насвистел(а) {user2}
насвистеть: 🎶 {user1} насвистел(а) для {user2}
насмешить: 🤣 {user1} насмешил(а) {user2}
насолить: 🧂 {user1} насолил(а) {user2}
наставить ремня: 🪶 {user1} наставил(а) ремня {user2}
насыпать соли: 🧂 {user1} насыпал(а) соли на {user2}
нюх: 👃 {user1} понюхал(а) {user2}
нюхать: 👃 {user1} понюхал(а) {user2}
няшить: 🫶 {user1} отняшил {user2}
обезвредить: 🧯 {user1} обезвредил(а) {user2}
обернуть в одеяло: 🛏️ {user1} обернул(а) {user2} в одеяло
облизать: 👅 {user1} облизнул(а) {user2}
облить бензином: ⛽ {user1} облил(а) бензином {user2}
облить водой: 💧 {user1} облил(а) водой {user2}
обмотать верёвкой: 🪢 {user1} обмотал(а) {user2} верёвкой
обмотать лентой: 🎀 {user1} обмотал(а) {user2} лентой
обмотать скотчем: 📦 {user1} обмотал(а) {user2} скотчем
обмотать шею ленточкой: 🎀 {user1} обмотал(а) шею {user2} ленточкой
обнять: 🤗 {user1} обнял(а) {user2}
обнять и гладить: 🫳 {user1} обнял(а) {user2} и гладит по голове
обнять крепко: 🫂 {user1} крепко обнял(а) {user2}
обнять нежно: 🫰 {user1} нежно обнял(а) {user2}
обнять с размаху: 🛫 {user1} обнял(а) {user2} с размаху
обнять сзади: 🤗 {user1} обнял(а) {user2} сзади
обрызгать: 💦 {user1} обрызгал(а) {user2}
обрызгать духами: 🌺 {user1} обрызгал(а) духами {user2}
обслюнявить: 🤤 {user1} обслюнявил(а) {user2}
одеть в костюм горничной: 🧹 {user1} одел(а) {user2} в костюм горничной
окатить водой: 💧{user1} окатил водой {user2}
окатить спермой: 💧💦{user1} окатил спермой {user2}
оседлать: 🐎 {user1} оседлал(а) {user2}
осмотреть: 🔍 {user1} осмотрел(а) {user2}
осыпать лепестками: 🌸 {user1} осыпал(а) лепестками {user2}
отгрызть инет: 🦷 {user1} отгрыз(ла) инет у {user2}
открыть окно: 🪟 {user1} открыл(а) окно из-за {user2}
откусить пирожок: 🥟 {user1} откусил(а) пирожок у {user2}
отлисить: '{user1} отлисил {user2}'
отправить в бан: 🔨 {user1} отправил(а) {user2} в бан
отправить в гулаг: 🏔️ {user1} отправил(а) {user2} в ГУЛАГ
отправить в ссылку: 🚂 {user1} отправил(а) {user2} в ссылку
отшлёпать: 🍑 {user1} отшлёпал(а) {user2}
перепугать до икоты: 😱 {user1} перепугал(а) {user2} до икоты
плеснуть чаем: 🍵 {user1} плеснул(а) чаем в {user2}
плюнуть семечкой: 🌻 {user1} плюнул(а) семечкой в {user2}
пнуть: 👢 {user1} пнул(а) {user2}
пнуть по самооценке: 🥾 {user1} пнул(а) по самооценке {user2}
пнуть под зад: 👢 {user1} пнул(а) {user2} под зад
пнуть тапком: 👟 {user1} пнул(а) тапком {user2}
поверить в: 🙏 {user1} поверил(а) в {user2}
повесить лапшу на уши: 🍝 {user1} повесил(а) лапшу на уши {user2}
погладить: 🤲 {user1} погладил(а) {user2}
погладить животик: 🐾 {user1} погладил(а) животик {user2}
погладить по голове: 🐾 {user1} погладил(а) {user2} по голове
погладить по спинке: 🫱 {user1} погладил(а) {user2} по спинке
погладить по щёчке: 🫰 {user1} погладил(а) {user2} по щёчке
погрозить пальцем: ☝️ {user1} погрозил(а) пальцем {user2}
под хвост: 🍑 {user1} дал(а) под хвост {user2}
подарить машину: 🚗 {user1} подарил машину {user2}
подбодрить: 🙌 {user1} подбодрил(а) {user2}
поделиться: 🤝 {user1} поделился(ась) с {user2}
поджечь: 🔥 {user1} поджёг(ла) {user2}
подзатыльник: ✋ {user1} дал(а) подзатыльник {user2}
подколоть: 😏 {user1} подколол(а) {user2}
подлизаться: 🧈 {user1} подлизался(ась) к {user2}
подлить масло в огонь: 🛢️ {user1} подлил(а) масла в огонь у {user2}
подложить свинью: 🐷 {user1} подложил(а) свинью {user2}
подмигнуть: 😉 {user1} подмигнул(а) {user2}
поднять настроение: 🎈 {user1} поднял(а) настроение {user2}
подсечь: 🦵 {user1} подсёк(сделала подсечку) {user2}
подставить плечо: 🤝 {user1} подставил(а) плечо {user2}
подставить подножку: 🤼‍♂️ {user1} подставил(а) подножку {user2}
пожал руку: 🤝 {user1} пожал(а) руку {user2}
пожала руку: 🤝 {user1} пожал(а) руку {user2}
пожарить шашлык: 🔥 {user1} пожарил(а) шашлык вместе с {user2}
пожать руку: 🤝 {user1} пожал(а) руку {user2}
пожелать добра: 🤍 {user1} пожелал(а) добра {user2}
позлить: 😈 {user1} позлил(а) {user2}
поймать: 🫴 {user1} поймал(а) {user2}
поймать и держать: 👐 {user1} поймал(а) {user2} и держит
поймать и не отпускать: ✊ {user1} поймал(а) {user2} и не отпускает
положить в карман: 👖 {user1} положил(а) {user2} в карман
помахать лапкой: 👋 {user1} помахал(а) лапкой {user2}
помыть: 🧼 {user1} помыл(а) {user2}
понежиться: ☁️ {user1} понежился(ась) с {user2}
понежиться в кровати: 🛏️ {user1} понежился(ась) в кроватке с {user2}
понести: 🚶‍♂️ {user1} понёс(ла) {user2}
понести на ручках: 👐 {user1} понёс(ла) {user2} на ручках
понюхать: 👃 {user1} понюхал(а) {user2}
понюхать волосы: 🌸 {user1} понюхал(а) волосы {user2}
понянчить: 🍼 {user1} понянчил(а) {user2}
поправить причёску: 💇‍♀️ {user1} поправил(а) причёску {user2}
порычать: 🐯 {user1} порычал(а) на {user2}
посадить в угол: 🪑 {user1} посадил(а) в угол {user2}
посмотреть томно: 👁️ {user1} томно посмотрел(а) на {user2}
поставить в угол: 📏 {user1} поставил(а) {user2} в угол
посыпать блёстками: ✨ {user1} посыпал(а) блёстками {user2}
потереть спину: 🫧 {user1} потер(ла) спинку {user2}
похитить: 🕶️ {user1} похитил(а) {user2}
похлопать по спине: 👏 {user1} похлопал(а) {user2} по спине
поцеловать: 💋 {user1} поцеловал(а) {user2}
поцеловать в лоб: 💋 {user1} поцеловал(а) {user2} в лоб
поцеловать в носик: 👃 {user1} поцеловал(а) {user2} в носик
поцеловать в щёчку: 💋 {user1} поцеловал(а) {user2} в щёчку
почесать за ушком: 🐶 {user1} почесал(а) {user2} за ушком
почесать спинку: 🖐️ {user1} почесал(а) спинку {user2}
почухать: 🐾 {user1} почухал(а) {user2}
пошептать гадости: 🗣 {user1} прошептал(а) {user2} гадости
пощёчина: 🖐️ {user1} дал(а) пощёчину {user2}
привязать к кровати: 🪢 {user1} привязал(а) {user2} к кровати
прижать: 🫂 {user1} прижал(а) {user2} к себе
прижать к стене: 🧱 {user1} прижал(а) {user2} к стене
прижаться: 🤗 {user1} прижался(ась) к {user2}
прижаться щечкой: 🤗 {user1} прижался(ась) щечкой к {user2}
приласкать: 🤗 {user1} приласкал(а) {user2}
прильнуть к: 🤍 {user1} прильнул(а) к {user2}
приобнять: 🤗 {user1} приобнял(а) {user2}
приподнять: 👐 {user1} приподнял(а) {user2}
приподнять подбородок: 🫱 {user1} приподнял(а) подбородок {user2}
присвоить: 🪙 {user1} присвоил(а) {user2}
причесать: 💇 {user1} причесал(а) {user2}
причинить боль: 🩸 {user1} причинил(а) боль {user2}
прищемить палец: 🔧 {user1} прищемил(а) палец {user2}
проглотить: 😋 {user1} проглотил(а) {user2}
продать: 💰 {user1} продал(а) {user2}
продать в рабство: 🔗 {user1} продал(а) в рабство {user2}
продать на органы: 🧠 {user1} продал(а) {user2} на органы
проиграл в карты: 🃏 {user1} проиграл(а) {user2} в карты
протянуть лапку: 🐾 {user1} протянул(а) лапку {user2}
протянуть печеньку: 🍪 {user1} протянул(а) печеньку {user2}
раздеть: 🩲 {user1} раздел(а) {user2}
раздражать: 😈 {user1} раздразнил(а) {user2}
размазать: 🖌️ {user1} размазал(а) {user2}
размазать по стенке: 🩸 {user1} размазал(а) {user2} по стенке
разоружить: 🛡️ {user1} разоружил(а) {user2}
раскулачить: 🪙 {user1} раскулачил(а) {user2}
расстрелять: 🔫 {user1} расстрелял(а) {user2} (игрушечным пистолетом)
растаять в объятиях: 💞 {user1} растаял(а) в объятиях {user2}
растрепать волосы: 💇 {user1} растрепал(а) волосы {user2}
растрогать: 🥹 {user1} растрогал(а) {user2}
расцарапать спину: 🐾 {user1} расцарапал(а) спинку {user2}
сварить борщ: 🥣 {user1} сварил(а) борщ для {user2}
связать ноги: 🦶 {user1} связал(а) ноги {user2}
сделать комплимент: 🌹 {user1} сделал(а) комплимент {user2}
сделать массаж: 💆‍♀️ {user1} сделал(а) массаж {user2}
сделать подножку: 🦶 {user1} сделал(а) подножку {user2}
сделать своим фембойчиком: 🌈 {user1} сделал(а) {user2} своим фембойчиком
сесть на коленки: 🪑 {user1} сел(а) на коленки {user2}
сесть на лицо: 🍑 {user1} сел(а) на лицо {user2}
слюнявить: 🤤 {user1} обслюнявил(а) {user2}
снести: 💥 {user1} снёс(снесла) {user2}
спеть серенаду: 🎤 {user1} спел(а) серенаду для {user2}
спился: 🥃 {user2} спился
стрельнуть глазками: 👁️‍🗨️ {user1} стрельнул(а) глазками в {user2}
тискать: 👐 {user1} затискал(а) {user2}
ткнуть: 👉 {user1} ткнул(а) {user2}
толкнуть: 🌀 {user1} толкнул(а) {user2}
тыкать: 👉 {user1} ткнул(а) {user2}
убил: ☠️ {user1} 'убил(а)' {user2} (в шутку)
убить: ☠️ {user1} 'убил(а)' {user2} (в шутку)
угостить тортиком: 🍰 {user1} угостил(a) {user2} вкусным тортиком
ударить: 🥊 {user1} ударил(а) {user2}
ударить дипломом: 🎓 {user1} ударил(а) дипломом {user2}
ударить током: ⚡ {user1} ударил(а) током {user2}
уделить внимание: 👀 {user1} уделил(а) внимание {user2}
уделить заботу: 🫶 {user1} уделил(а) заботу {user2}
уделить ласку: 💞 {user1} уделил(а) ласку {user2}
удержать силой: 💪 {user1} удержал(а) {user2} силой
удушить: 🫢 {user1} удушил(а) {user2}
удушить любовью: ❤️‍🔥 {user1} удушил(а) {user2} любовью
украсть: 🕵️ {user1} украл(а) {user2}
украсть сердце: ❤️ {user1} украл(а) сердце {user2}
укусить: 🐾 {user1} укусил(а) {user2}
укусить за щёчку: 😈 {user1} укусил(а) {user2} за щёчку
укутать в заботу: 🧣 {user1} укутал(а) {user2} в заботу
уложить спать: 😴 {user1} уложил(а) спать {user2}
усадить на колени: 🪑 {user1} усадил(а) {user2} на колени
усадить на облако: ☁️ {user1} усадил(а) {user2} на облако
усадить на трон: 👑 {user1} усадил(а) {user2} на трон
успокоить: 🫂 {user1} успокоил(а) {user2}
утащить силком: 💼 {user1} утащил(а) {user2} силком
утешить: 🫶 {user1} утешил(а) {user2}
утонуть в ляшках: 🌊 {user1} утонул(а) в ляшках {user2}
царапнуть: 🐾 {user1} царапнул(а) {user2}
целовать: 💋 {user1} поцеловал(а) {user2}
чмок: 😘 {user1} чмокнул(а) {user2}
чмокнуть: 😘 {user1} чмокнул(а) {user2}
швырнуть: 🏌️ {user1} швырнул(а) {user2}
швырнуть тапком: 🥿 {user1} швырнул(а) тапком в {user2}
швырнуть холодильник: 🧊 {user1} швырнул(а) в {user2} холодильник
шепнуть на ушко: 🫢 {user1} шепнул(а) {user2} на ушко
шлёп: 🍑 {user1} шлёпнул(а) {user2}
шлёпать: 🍑 {user1} шлёпнул(а) {user2}
шлёпнуть: 🍑 {user1} шлёпнул(а) {user2}
шлёпнуть газеткой: 📰 {user1} шлёпнул(а) {user2} газеткой
щекотать: 😄 {user1} пощекотал(а) {user2}
щелбан: 🖕 {user1} дал(а) щелбан {user2}
