BOT_TOKEN: "7938708472:AAE3DKLhduzrzD50e8BKavH1NzsEkBl7CHw"

COMMANDS_CONFIG:
  r:
    text: |
      Общие положения

      1.1 Незнание правил не освобождает от ответственности.
      1.2 Правила могут изменяться в любое время.
      1.2.1 Правила могут быть изменены после предложения участников канала и подтверждено хвостами РПС.
      1.3 Правила распространяются на всех участниках канала без исключения.
      1.4 Не разрешается находить лазейки в правилах, а также обходить наказания любым способом.
      1.5 Не нравится, как ведётся канал — можешь предложить улучшение или поплакать в подушку.

      Поведение на сервере

      2.1 Запрещено любое поведение, которое может нанести вред другим участникам, включая оскорбления (в том числе использование нецензурной лексики по отношению к другим участникам канала), не скрытые спойлером, угрозы, токсичность и неадекватность, провокации конфликтов, издевательства.
      2.2 Запрещено распространять информацию о человеке без его согласия.
      2.3 Запрещена любая реклама, несогласованная с администрацией.
      2.3.1 Запрещена полностью реклама наркотиков, nsfw контента, финансовых пирамид, казино, оружия и прочее.
      2.4 Запрещён спам.
      2.6 Запрещён NSFW контент без согласованнийя с администрацией. Для NSFW контента без согласования с администрацией существует отдельный чат - https://t.me/fluffytableknights.
      2.7 Основная тема канала - sewayaki kitsune no senko-san.
      2.7.1 Неуважение к теме канала будут наказываются баном или мутом.

      Нарушения и наказания

      3.1 Администрация имеет право определять, что нарушает правила, а что нет.
      3.1.1 В случае, если администрация сама нарушает правила, можно обратиться человеку выше по иерархии.
      3.1.2 Иерархия - Первый Хвост (Адм) --> Второй Хвост (Адм) --> Третий Хвост (Адм) --> Ст. Модератор (Адм) (Мод) --> Модератор (Адм) (Мод) --> Мл. Модератор (Адм) (Мод) --> Обычный пользователь.
      3.1.3 В случае нарушения правил Первым Хвостом, писать Богу (любой ответственный).

      3.2 Тяжесть нарушения обычного пользователя определяется администрацией.
      3.2.1 При обходе наказания, наказание увеличивается в зависимости от тяжести нарушения.
      3.2.2 Тяжесть нарушения модерации определяется Хвостами.

      3.3 Администрация вправе самостоятельно определять необходимые меры пресечения.
      3.3.1 Пресечение свыше 7 дней должно быть подтверждено одним из хвостов РПС.
      3.3.2 В случае отсутствия Хвостов РПС, пресечение только на 7 дней до разбирательств.
      3.3.3 Хвосты должны быть упомянуты о пресечении и о том, что требуется их разбирательство.
    warning: "⚠️ Господин, правила уже показаны..."
    flag: rules
    cooldown: 180

  help:
    text: |
      Справка по Горничной РПС

      /r - Приказывает горничной показать участникам правила этого места и через 3 минуты убрать их.
      /help - Приказывает горничной показать участникам справку её способностей и через 3 минуты убрать её.
      /ds - Приказывает горничной показать участникам ссылку на ДС сервер РПС.

      Также вы можете поцеловать участника, или обнять его — попробуйте поэкспериментировать с этим :)

      /addact - позволяет добавлять новое действие!
      /delact - позволяет удалять действие!
    warning: "⚠️ Господин, справка уже показана..."
    flag: help
    cooldown: 180

  ds:
    text: "🔗 Discord – https://discord.gg/QkN8TkUJgK"
    warning: "⚠️ Господин, ссылка на дискорд уже показана..."
    flag: discord
    cooldown: 180

GAGS:
  - "надеть кляп"
  - "надеть шариковый кляп"

UNGAGS:
  - "вынуть кляп"

MUMBLES:
  - "Мммпх"
  - "Мррх"
  - "Мннф~"
  - "*приглушённый стон*"

ADMINS:
  - 1830141800
